### PR TITLE
B23 margie

### PR DESCRIPTION
**Pull request by tmayan**
margie i saw your new branch

### CODE REVIEW

**Comment by tmayan** [comment]
please review margie's code

**Comment by mucahitekin** [comment]
static{
}

**Review by ShirinZiyovuddionva — COMMENTED** [review]
Cool code Margie

**Review by mucahitekin — COMMENTED** [review]
that is correct

**Review by akalexiskelly — APPROVED** [review]
this looks great Margie - job well done : )

**Review by turgayozkan78 — COMMENTED** [review]
good

**Review by MemetKayaQA — COMMENTED** [review]
those codes are helpful

**Review by mucahitekin — COMMENTED** [review]
margi add more awesome codes please

**Pull request merged**
