### PR TITLE
Practice

### PR DESCRIPTION
**Pull request by tmayan**
good job!

### CODE REVIEW

**Review by turgayozkan78 — APPROVED** [review]
good

**Review by MemetKayaQA — COMMENTED** [review]
thanks

**Comment by tmayan** [comment]
is anybody know how to do change request ? do we need to do after merging branch or in this step?

**Comment by mucahitekin** [comment]
memet add more codes please

**Review by maggan1968 — COMMENTED** [review]
nice

**Comment by MemetKayaQA** [comment]
I didnt understand that part to Tugba

**Comment by mucahitekin** [comment]
since we are working this, we cant fully focus. to teaher

**Comment by turgayozkan78** [comment]
I can see your request but I cannot assign you as request

**Pull request merged**
