### PR TITLE
My test is done

### PR DESCRIPTION
**Pull request by zaurabbasov**

### CODE REVIEW

**Comment by tmayan** [comment]
good job

**Review by MemetKayaQA — CHANGES_REQUESTED** [review]
add some more codes Zaur

**Review by zaurabbasov — COMMENTED** [review]
Good code

**Comment by tmayan** [comment]
how can you add change request memet ?

**Review by mucahitekin — COMMENTED** [review]
zaur added the static block, please

**Review by ShirinZiyovuddionva — COMMENTED** [review]
cool code Zaur

**Review by akalexiskelly — COMMENTED** [review]
good!

**Comment by turgayozkan78** [comment]
good

**Comment by MemetKayaQA** [comment]
Tugba you mean request more infor by comment ?

**Pull request merged**
