### PR TITLE
Bitcoin

### PR DESCRIPTION
**Pull request by tmayan**
hi

### CODE REVIEW

**Comment by tmayan** [comment]
good

**Review by akalexiskelly — COMMENTED** [review]
to the moonnnnnnnnnnn

**Review by mucahitekin — COMMENTED** [review]
doge coin will be 10 cent before goes up :)

**Review by MemetKayaQA — APPROVED** [review]
done

**Comment by tmayan** [comment]
good

**Review by zaurabbasov — COMMENTED** [review]
Good

**Comment by mucahitekin** [comment]
margi what are tryin to find?

**Review by zaurabbasov — COMMENTED** [review]
Perfect

**Pull request merged**
